name: flutter_complete_clean
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.2.3

dependencies:
  cli_util: ^0.4.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
